name: Pipeline
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11.4
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.4
    - name: Install dependencies
      run: |
        make install
    - name: Lint with pylint
      run: |
        make lint
    - name: Test with pytest
      run: |
        make test
    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.PRIVATE_KEY }}
        script: |
          cd ${{ secrets.APP_PATH }}
          git pull
          docker-compose up -d --build
          echo "Deploy finalizado"
